sensiblecodeio/hookbot

main.go
The new types `Message` and `Listener` have been created which add a `Suffix` to what was previous a bare `[]byte` and a `chan []byte` respectively.
=> Separate notifications into namespaces by URL

auth_test.go, main.go, util.go
Note! You *will* need to upgrade wscat if you use it:
https://github.com/pwaller/wscat/pull/1
See the below links for the rationale.
https://groups.google.com/d/topic/golang-nuts/so5wHa57RoM/discussion
https://github.com/gorilla/websocket#gorilla-websocket-compared-with-other-packages
https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+x%2Fnet%2Fwebsocket
=> Use gorilla/websocket

main.go
* Renamed make-token to make-tokens
* Improved workflow for using tokens
Now, rather than having to make a token and then construct a URL with cumbersome editing of long tokens, the output is directly useful.
For example, now it's easy to do the following for testing:
```
export HOOKBOT_KEY=foo
hookbot serve
wscat $(hookbot make-tokens /sub/foo)
curl -d 'message' $(hookbot make-tokens /pub/foo)
```
=> Improvements to make-tokens

main.go, request_json.go, request_json_test.go
This is because consumers may need to know information only present in the headers.
=> Serialize whole request

auth_test.go, main.go, topic_test.go
* Implement selective topic strobing via map rather than comparison for every listener
* Add test that topics are working correctly
* (maybe): make topics hierarchical
On the last point, for example, you can subscribe to everything under github scraperwiki via:
`/sub/github.com/scraperwiki/`
=> Improvements to topics

main.go, topic_test.go
Current implementation tests each topic for the `?recursive` string suffix.
If that suffix is present, it then tests if the message being delivered has
a candidate `?recursive` topic as its prefix, and if so, the message goes there.
=> Add ?recursive for recursive watching of topics

main.go, pkg/hookbot/auth_test.go, pkg/hookbot/hookbot.go, pkg/hookbot/router.go, pkg/hookbot/topic_test.go, pkg/listen/listen.go, pkg/router/github/github.go
This changeset significantly reduces the memory requirements and also
improves the behaviour with lagging receivers and dropped messages.
In the worst case if all of the internal buffers somehow manage to get full,
POST'ing clients are now notified that their message couldn't be delivered,
too.
The main change here was to instead of spinning up a goroutine per sent message,
(just to have a timeout on that send), now there are worker goroutines which
handle a limited number of timeouts at once.
The performance is fairly significantly improved and has been measured to be
in excess of 70 msgs/sec to 1,000 clients before messages start getting dropped.
None of these changes were particularly needed for ScraperWiki's purposes, though
they did shake out a few bugs. They were mainly made so that …
=> Significantly reduce memory consumption

pkg/listen/listen.go
This bug meant that users would keep adding more authorization headers
on every retry.
=> Avoid modifying caller's header value in Watch()

pkg/listen/listen.go
These were a debugging artefact which unfortunately made it into production.
=> Eliminate ping/pong messages

main.go
Would have found this useful today to see which version I had installed. Without this, it only shows `0.0.0`.
=> Display version number at command line

main.go
Endpoints of the form `pub/kitten` look good but don't work: needs to be `/pub/kitten`
=> Require endpoints to start with /

pkg/hookbot/hookbot.go
Instead of just sending the body, also send the full topic, so
subscribers can make decisions based on the original topic.
The topic is ended by a NUL character. This was chosen
because `%00`s in URIs are recognised as being problematic and
"should be rejected if the application is not expecting ... raw data"
=> Prepend topic when ?recursive (NUL delimited)

pkg/hookbot/auth.go, pkg/hookbot/auth_test.go
Resolves #24.
Now if you visit a /sub/ endpoint without the proper credentials, you
aways see 401, rather than 404.
This doesn't leak information, since all /sub/ endpoints always exist.
=> Add 401 Unauthorized response

README.md, pkg/hookbot/auth.go, pkg/hookbot/auth_test.go
So if you have a valid key for /pub/dog/, you can also use that key
for /pub/dog/cat/owl etc. Only / terminated substrings (and the
original string itself) are considered.
=> Search subpaths for HMAC matches

pkg/hookbot/auth.go, pkg/hookbot/auth_test.go, pkg/listen/listen.go
This makes it possible to have a token which is valid for both pub and sub.
The mechanism is to make a token for `/foo` which is valid for both `/sub/foo` and `/sub/foo`.
=> Add pub/sub auth-agnostic endpoints

pkg/hookbot/hookbot.go, pkg/hookbot/hookbot_test.go, pkg/listen/listen.go
If /pub/ or /sub/ is specified, these are only allowed for publish or
subscribe.
In this new implementation, if they are missing, the URLs are allowed for both
publish and subscribe.
=> Make URLs lacking /(pub|sub) both pub and sub

README.md, main.go
Add support for TLS without need for a proxy.
(tiny-ssl-reverse-proxy works well, but complicates things like handling origins other than sameorigin)
=> Support TLS

go.mod, go.sum
Fixes a [security issue](https://github.com/gorilla/websocket/releases/tag/v1.4.1).
=> Update gorilla/websocket to v1.4.1

go.mod, go.sum, main.go, pkg/hookbot/router.go, pkg/router/github/github.go
This package moved locations on GitHub.
Have set the version to v1.20 still as it's known good for hookbot.
The later 1.2x versions have some regression that I don't know
whether it impacts hookbot: urfave/cli#850 and has only recently
been fixed, without a later 1.2x fixed version released yet.
=> Update import for codegangsta/cli to urfave/cli

.github/workflows/ci-build.yml
So that it isn't unintentionally broken without noticing.
=> Check the Docker build

.github/workflows/ci-build.yml
Now covered by the Docker build.
=> Remove redundant `go get -v`

.github/workflows/ci-release.yml
For build on tag, so that the release is built by GitHub.
=> Add release workflow
